# Generated by Django 5.2.6 on 2025-09-04 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carriage_number', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('class_type', models.CharField(choices=[('first', 'First Class'), ('second', 'Second Class')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance')], default='active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('carriage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Train.carriage')),
            ],
        ),
        migrations.AddField(
            model_name='carriage',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Train.train'),
        ),
        migrations.CreateModel(
            name='TrainSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_location', models.CharField(max_length=100)),
                ('final_destination', models.CharField(max_length=100)),
                ('departure_date', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('on_time', 'On Time'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='on_time', max_length=50)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='Train.train')),
            ],
        ),
    ]
