# Generated by Django 5.2.6 on 2025-09-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Train', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainschedule',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
        ),
    ]
