# Generated by Django 5.2.6 on 2025-09-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Train', '0002_trainschedule_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainschedule',
            name='status',
            field=models.CharField(choices=[('on_time', 'On Time'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled'), ('outdated', 'Outdated')], default='on_time', max_length=50),
        ),
    ]
